name: Build 5.15.189 kernel for S905L3B

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build 5.15.189 kernel (Amlogic)
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel          # 只编内核
          kernel_source: ophub/kernel
          kernel_version: 5.15.189
          kernel_auto: false
          kernel_config: true
          kernel_package: all           # 只生成 headers + modules
          kernel_sign: -s905l3b
